services:
  postgres:
    image: postgres:17
    container_name: inventory-service-postgres
    ports:
      - "5442:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ajay
      POSTGRES_DB: order-service
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql